name: Node.js CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 18
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
    - run: npm i
    - run: npm run build --if-present
    - run: git add dist
    - run: git diff --quiet && git diff --staged --quiet || git commit -m "dist build"
    - run: git pull origin master
    - run: git push origin master
  deploy:
    runs-on: self-hosted
    steps:
      - run: cp -r ~/actions-runner/_work/api.web/api.web/* ~/docker/volumes/api.web/.
      # - run: ~/docker/docker-compose down
      # - run: ~/docker/docker-compose up -d